max_obj_num: 10
modelnet_path: "<full path to modelnet dataset>/ModelNet40"
save_path: "<path to save generated dataset>"
num_examples: 2000
split: "test"
skip_3d_image_gen: false
skip_3d_html_gen: false